

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Hu4bSrLyMxG
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import React, { SVGProps } from 'react';

export default function ProfileComponent() {
  return (
    <div className="bg-white">
      <div className="bg-[#41a342] p-4 text-white">
        <h1 className="text-3xl">Profile</h1>
      </div>
      <div className="max-w-4xl mx-auto my-8 p-8 border rounded-md">
        <h2 className="text-2xl font-semibold mb-6">Edit Profile</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="md:col-span-2">
            <div className="flex items-center mb-4">
              <UserIcon className="text-gray-500 mr-2" />
              <Input placeholder="Super Admin" type="text" />
            </div>
            <div className="flex items-center mb-4">
              <MailboxIcon className="text-gray-500 mr-2" />
              <Input placeholder="admin@extremelab.tech" type="email" />
            </div>
            <div className="flex items-center mb-4">
              <LockIcon className="text-gray-500 mr-2" />
              <Input placeholder="••••••••" type="password" />
            </div>
            <div className="flex items-center mb-4">
              <LockIcon className="text-gray-500 mr-2" />
              <Input placeholder="Password Confirmation" type="password" />
            </div>
            <div className="flex items-center mb-4">
              <FileSignatureIcon className="text-gray-500 mr-2" />
              <Input type="file" />
            </div>
          </div>
          <div className="md:col-span-1">
            <div className="flex flex-col items-center justify-center p-4 border rounded-md h-full">
              <img
                alt="Signature"
                className="mb-4"
                height="128"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "128/128",
                  objectFit: "cover",
                }}
                width="128"
              />
              <Button className="bg-[#bd1e59] text-white">Browse</Button>
            </div>
          </div>
        </div>
        <div className="mt-6">
          <Button className="bg-[#bd1e59] text-white">Save</Button>
        </div>
      </div>
    </div>
  )
}


function UserIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function MailboxIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z" />
      <polyline points="15,9 18,9 18,11" />
      <path d="M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2v0" />
      <line x1="6" x2="7" y1="10" y2="10" />
    </svg>
  )
}


function LockIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}


function FileSignatureIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 19.5v.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8.5L18 5.5" />
      <path d="M8 18h1" />
      <path d="M18.42 9.61a2.1 2.1 0 1 1 2.97 2.97L16.95 17 13 18l.99-3.95 4.43-4.44Z" />
    </svg>
  )
}
