/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/B1EXAbzCexZ
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"


export function Exrad() {
  return (
    <div className="flex h-screen bg-[#2d3436]">
    
      <main className="flex-1 bg-gray-100">
      
        <div className="px-6 py-4">
          <h3 className="text-2xl font-medium text-gray-700">Dashboard</h3>
          <div className="grid grid-cols-3 gap-6 mt-4">
            <div className="p-4 bg-[#e74c3c] rounded-lg shadow-md">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-semibold text-white">76</h4>
                  <p className="text-sm text-white">Tests</p>
                </div>
                <FlaskRoundIcon className="w-8 h-8 text-white" />
              </div>
              <a className="text-xs text-white underline" href="#">
                More info
              </a>
            </div>
            <div className="p-4 bg-[#e74c3c] rounded-lg shadow-md">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-semibold text-white">254</h4>
                  <p className="text-sm text-white">Patients</p>
                </div>
                <UserIcon className="w-8 h-8 text-white" />
              </div>
              <a className="text-xs text-white underline" href="#">
                More info
              </a>
            </div>
            <div className="p-4 bg-[#e74c3c] rounded-lg shadow-md">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-semibold text-white">15</h4>
                  <p className="text-sm text-white">Contracts</p>
                </div>
                <FileSignatureIcon className="w-8 h-8 text-white" />
              </div>
              <a className="text-xs text-white underline" href="#">
                More info
              </a>
            </div>
            <div className="p-4 bg-[#e74c3c] rounded-lg shadow-md">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-semibold text-white">339</h4>
                  <p className="text-sm text-white">Invoices</p>
                </div>
                <DollarSignIcon className="w-8 h-8 text-white" />
              </div>
              <a className="text-xs text-white underline" href="#">
                More info
              </a>
            </div>
            <div className="p-4 bg-[#e74c3c] rounded-lg shadow-md">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-semibold text-white">339</h4>
                  <p className="text-sm text-white">Doctors</p>
                </div>
                <UserIcon className="w-8 h-8 text-white" />
              </div>
              <a className="text-xs text-white underline" href="#">
                More info
              </a>
            </div>
            <div className="p-4 bg-[#e74c3c] rounded-lg shadow-md">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-lg font-semibold text-white">339</h4>
                  <p className="text-sm text-white">Bookings</p>
                </div>
                <CalendarCheckIcon className="w-8 h-8 text-white" />
              </div>
              <a className="text-xs text-white underline" href="#">
                More info
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
import React, { SVGProps } from 'react';

function MenuIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function SearchIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function BellIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function FlaskRoundIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 2v7.31" />
      <path d="M14 9.3V1.99" />
      <path d="M8.5 2h7" />
      <path d="M14 9.3a6.5 6.5 0 1 1-4 0" />
      <path d="M5.52 16h12.96" />
    </svg>
  )
}


function UserIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function FileSignatureIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 19.5v.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8.5L18 5.5" />
      <path d="M8 18h1" />
      <path d="M18.42 9.61a2.1 2.1 0 1 1 2.97 2.97L16.95 17 13 18l.99-3.95 4.43-4.44Z" />
    </svg>
  )
}


function DollarSignIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}


function CalendarCheckIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="m9 16 2 2 4-4" />
    </svg>
  )
}
